feat:new-css-for-new-page
dashpay/wp-dash-theme pull request #148
Opened 2022-11-01 16:47 UTC by Silvanasss

2022-11-02 08:27 UTC, strophy commented on assets/dash.css
> +	content: url(https://staging-wp.dash.org/wp-content/uploads/esports-arrow.png);
This needs to be a relative URL, not an absolute URL to our staging server

2022-11-02 08:30 UTC, strophy requested changes
Need to change one URL and add a commit to bust cache

2022-11-04 10:34 UTC, Silvanasss commented
Check please @strophy I have changed to the previous one and boosted Cache

2022-11-04 11:11 UTC, strophy approved these changes

2022-11-08 10:34 UTC, merged